//! Integration test: a real BatVu scan, on the wire, through the whole stack.
//!
//! The fixture is not hand-written. `batvu_living_room.ultrasonic.jsonl` is
//! generated by BatVu's own `npm run artifacts` — 72 pings of its simulated
//! living-room scene, written by the TypeScript emitter in `@batvu/field` — and
//! copied here verbatim. That makes this the integration's only cross-language
//! conformance check: if BatVu's emitter and this parser ever disagree about
//! the schema, one of the two repositories fails to build, rather than a
//! deployment failing to ingest.
//!
//! # What this proves, and what it does not
//!
//! It proves that RuField ingests real ultrasonic range profiles from a
//! commodity phone pipeline and produces well-formed, signed, trust-verified
//! events from them. That is the win, and it is a real one: `Modality::Ultrasonic`
//! has been code 7 in the registry since v0.1 with nothing implementing it.
//!
//! It does not prove accuracy. The recording is simulator output, so every
//! event is `synthetic: true` and is fusable only under simulation trust. And
//! it does not produce an inference — see `the_shipped_rules_have_no_predicate_a_range_only_sensor_can_drive`,
//! which asserts that outcome deliberately rather than papering over it.

use rufield_adapters::{
    UltrasonicConfig, UltrasonicOutput, UltrasonicReplayAdapter, UltrasonicSource,
};
use rufield_core::{
    Destination, FieldAdapter, FieldAxis, FusionEngine, InferenceQuery, Modality, PrivacyClass,
    PrivacyDecision,
};
use rufield_fusion::{RuFieldFusion, RuleSet};
use rufield_privacy::DefaultPrivacyGuard;
use rufield_provenance::{verify_event, TrustPolicy, TrustVerifier};

const BATVU_SCAN: &str = include_str!("fixtures/batvu_living_room.ultrasonic.jsonl");

fn adapter() -> UltrasonicReplayAdapter {
    UltrasonicReplayAdapter::from_jsonl_with(
        BATVU_SCAN,
        UltrasonicConfig {
            accept: UltrasonicSource::Simulated,
            zone_id: "living_room".into(),
            placement: "handheld".into(),
            output: UltrasonicOutput::CoarseProfile,
        },
    )
    .expect("parse the BatVu fixture")
}

#[test]
fn the_batvu_fixture_parses_and_every_event_is_well_formed() {
    let mut adapter = adapter();
    assert_eq!(adapter.ping_count(), 72, "the fixture is a 72-ping sweep");
    assert_eq!(adapter.device_id(), "batvu-reference-01");
    assert_eq!(adapter.modality(), Modality::Ultrasonic);

    let receipt = adapter.calibrate("living_room").expect("calibrate");
    assert_eq!(receipt.modality, "ultrasonic");
    assert!(receipt.data_hash.starts_with("sha256:"));

    let events = adapter.collect_events().expect("collect");
    assert_eq!(events.len(), 72);

    let mut previous = 0u64;
    for event in &events {
        event
            .validate_evidence_at(event.timestamp_ns)
            .expect("structural evidence invariants hold");
        verify_event(event).expect("the signature verifies");

        assert_eq!(event.tensor.modality, Modality::Ultrasonic);
        assert_eq!(event.tensor.axes, vec![FieldAxis::Range]);
        assert_eq!(event.sensor.vendor, "batvu");
        assert_eq!(
            event.tensor.calibration_id.as_deref(),
            Some(receipt.calibration_id.as_str())
        );

        // The wire has no finiteness check — `FieldTensor::validate` looks only
        // at shape and axis rank — so a NaN would serialize as JSON `null` and
        // then fail to deserialize as an f32 on the far side of the wire. The
        // parser rejects it at the source; this is the assertion that says so.
        assert!(
            event
                .tensor
                .values
                .iter()
                .all(|v| v.is_finite() && *v >= 0.0),
            "every profile value is finite and non-negative"
        );

        // rufield's replay watermark requires strictly increasing timestamps
        // per device, in every trust mode, and silently drops what does not
        // advance. A 15 Hz sweep has 66 ms of headroom; this is what confirms
        // the emitter used it.
        assert!(
            event.timestamp_ns > previous,
            "timestamps strictly increase"
        );
        previous = event.timestamp_ns;
    }

    // Event ids are unique, which the watermark's duplicate check requires.
    let mut ids: Vec<&str> = events.iter().map(|e| e.event_id.as_str()).collect();
    ids.sort_unstable();
    ids.dedup();
    assert_eq!(ids.len(), events.len());
}

#[test]
fn a_real_scan_survives_the_whole_trust_and_privacy_chain() {
    let mut adapter = adapter();
    adapter.calibrate("living_room").expect("calibrate");
    let events = adapter.collect_events().expect("collect");

    // Simulation trust, because the recording declares itself simulated and the
    // adapter derives `synthetic` from that rather than from a caller flag.
    let mut trust = TrustVerifier::simulation();
    let guard = DefaultPrivacyGuard::default();

    for event in &events {
        trust
            .verify_and_record_at(event, event.timestamp_ns)
            .expect("trust accepts a simulated recording under simulation policy");
        // The coarse profile is P1, which the stock policy allows onto a
        // network. This is the whole reason the adapter defaults to it.
        assert_eq!(
            guard.authorize_event(event, Destination::Network, false, false),
            PrivacyDecision::Allow
        );
    }

    // And the recording cannot be ingested twice: the watermark has advanced
    // past every event in it.
    assert!(
        trust
            .verify_and_record_at(&events[0], events[0].timestamp_ns)
            .is_err(),
        "a replayed recording is refused"
    );
}

#[test]
fn the_raw_profile_mode_is_edge_local_and_the_policy_says_so() {
    let mut raw = UltrasonicReplayAdapter::from_jsonl_with(
        BATVU_SCAN,
        UltrasonicConfig {
            output: UltrasonicOutput::RangeProfile,
            ..Default::default()
        },
    )
    .expect("parse");
    let events = raw.collect_events().expect("collect");
    let guard = DefaultPrivacyGuard::default();

    assert_eq!(events[0].tensor.privacy_class, PrivacyClass::P0);
    // 256 bins as recorded, against the 32 the coarse mode serves.
    assert_eq!(events[0].tensor.values.len(), 256);
    assert!(matches!(
        guard.authorize_event(&events[0], Destination::Network, false, false),
        PrivacyDecision::Deny(_)
    ));
    assert_eq!(
        guard.authorize_event(&events[0], Destination::EdgeLocal, false, false),
        PrivacyDecision::Allow
    );
}

#[test]
fn fusion_ingests_every_event_without_error() {
    let mut adapter = adapter();
    adapter.calibrate("living_room").expect("calibrate");
    let events = adapter.collect_events().expect("collect");

    let mut engine = RuFieldFusion::new();
    for event in events {
        engine.ingest(event).expect("fusion accepts the event");
    }
}

/// The honest negative result, asserted rather than avoided.
///
/// A demo that fabricated a `presence` feature would light up the shipped
/// `person_present` rule and look like a success. It would also be a range-only
/// sensor asserting it can tell a person from a coat on the back of a chair.
/// So the adapter does not set `presence`, and the consequence is this: with
/// the shipped rules, a BatVu scan produces no inferences at all.
///
/// There are two independent reasons, and both are worth pinning, because
/// fixing only the first would look like progress and change nothing:
///
/// 1. No rule in `rules/room_state.toml` lists `"ultrasonic"` among its
///    `inputs`, so no rule ever sees the events.
/// 2. Even a rule that did would find nothing to fire on. The engine's `feat`
///    lookup handles `motion_energy`, `breathing_band`, `transient`,
///    `presence`, `posture_sit` and `posture_lie` — every one of them a
///    statement about a body. `range_m` reaches the fusion window but has no
///    `feat` arm, so a `weighted_bayes` rule on it scores 0.0; the only
///    predicate that reads it, `range_depart`, additionally requires
///    `motion_energy > 0.4`, which a phone standing still cannot supply.
///
/// The gap is therefore in the rule vocabulary, not in the adapter: RuField
/// v0.1 has no predicate for static geometry. Adding one is a change to
/// `rufield-fusion`, which is not what an adapter PR is for.
#[test]
fn the_shipped_rules_have_no_predicate_a_range_only_sensor_can_drive() {
    let mut adapter = adapter();
    adapter.calibrate("living_room").expect("calibrate");
    let events = adapter.collect_events().expect("collect");

    // Reason 1: the default ruleset does not list the modality.
    let mut default_engine = RuFieldFusion::new();
    for event in events.clone() {
        default_engine.ingest(event).expect("ingest");
    }
    let inferences = default_engine
        .infer(&InferenceQuery {
            zone_id: Some("living_room".into()),
            labels: vec![],
            track_id: None,
            as_of_ns: None,
        })
        .expect("infer");
    assert!(
        inferences.is_empty(),
        "no shipped rule accepts ultrasonic input"
    );

    // Reason 2: adding the modality is not enough. This ruleset names
    // "ultrasonic" explicitly and still produces nothing, because the feature
    // it would have to key on does not exist in the engine's vocabulary.
    let rules = RuleSet::from_toml(
        r#"
[rule.person_present]
inputs = ["ultrasonic"]
method = "weighted_bayes"
feature = "presence"
threshold = 0.40
privacy_max = "P2"
"#,
    )
    .expect("valid rules");

    let mut wired = RuFieldFusion::with_rules(rules);
    for event in events {
        wired.ingest(event).expect("ingest");
    }
    let inferences = wired
        .infer(&InferenceQuery {
            zone_id: Some("living_room".into()),
            labels: vec![],
            track_id: None,
            as_of_ns: None,
        })
        .expect("infer");
    assert!(
        inferences.is_empty(),
        "the adapter refuses to supply `presence`, so a presence rule cannot fire on it"
    );
}

#[test]
fn the_fixture_carries_the_range_on_the_key_fusion_reads() {
    let mut adapter = adapter();
    adapter.calibrate("living_room").expect("calibrate");
    let events = adapter.collect_events().expect("collect");

    let with_echo = events
        .iter()
        .find(|e| !e.observation.labels.contains(&"clear_path".to_string()))
        .expect("a 72-ping sweep of a furnished room detects something");

    // Both, because they are read by different consumers: the typed field by a
    // display, `features["range_m"]` by the fusion window. Setting only the
    // typed one produces an event that is wire-correct and invisible.
    assert!(with_echo.observation.range_m.is_some());
    assert_eq!(
        with_echo.observation.features.get("range_m").copied(),
        with_echo.observation.range_m
    );

    // And the features map carries nothing about a body.
    for forbidden in ["presence", "breathing_band", "posture_height", "transient"] {
        assert!(
            !with_echo.observation.features.contains_key(forbidden),
            "an ultrasonic event must not claim `{forbidden}`"
        );
    }
}

#[test]
fn the_fixture_cannot_be_read_as_a_device_capture() {
    // The recording declares `simulated`. An operator who points a
    // captured-replay deployment at it gets a hard refusal rather than a
    // silently upgraded trust tier — which is the entire purpose of the
    // `accept` field.
    let error = UltrasonicReplayAdapter::from_jsonl_with(
        BATVU_SCAN,
        UltrasonicConfig {
            accept: UltrasonicSource::DeviceCapture,
            ..Default::default()
        },
    )
    .expect_err("must refuse");
    assert!(error.to_string().contains("device_capture"));

    // And the same events under captured-replay TRUST are refused too, because
    // `synthetic: true` is rejected before any key lookup.
    let mut adapter = adapter();
    let events = adapter.collect_events().expect("collect");
    let mut replay = TrustVerifier::new(TrustPolicy::captured_replay(), Default::default());
    assert!(replay
        .verify_and_record_at(&events[0], events[0].timestamp_ns)
        .is_err());
}
